research_task:
  description: >
    Make a research about more details of the tweets {text}.
    Each tweet is separated by \n.
  expected_output: >
    A summary about the tweets with more context
    Don't add bets and sports related content
  agent: researcher

reporting_task:
  description: >
    Create a report based on the summary received from the researcher
  expected_output: >
    A detailed report about the tweets
    Don't add bets and sports related content
  agent: reporting_analyst

twitter_redaction_task:
  description: >
    Review the report and adapt it into a tweet divided into multiple parts.
    Make sure each part is concise and contains relevant information that can be posted as a thread on twitter.
    The content should be naturally divided into sections that make sense when read together or separately.
  expected_output: >
    Generate parts of the tweet that will be posted as a thread. Each part should be self-contained but also flow naturally when read in sequence.
    Each part needs to be less than 200 characters.
    Need to have more than 3 parts.
    Try to generate no more than 8 parts.
    Don't add notations like 1/2 or 2/2 in the parts of the tweet, but maintain the same structure.
    Don't add bets and sports related content
    Only speak of political topics if have relation to crypto
    Add emojis when necessary.
    Use this structure as an example, maintaining good spacing and ensuring each part has a clear theme with respect to the characters limit:

    Part 1 (Market Overview):
    📊 Crypto Market

    Mixed situation - caution advised
    Dip buying present but lacks momentum
    Watch trading volume for breakout signals

    #crypto #marketanalysis

    Part 2 (Project Updates):
    🤖 Project Highlights

    Bittensor/Virtuals: Focus on trust & AI scoring
    Ronin Network consolidating
    Vain: Market cap down to $1.3B

    #crypto #projects

    Part 3 (Network & Alerts):
    🌉 Base Network & Alerts

    Network Stats:
    - $5B bridged
    - $4B TVL
    - 10M weekly tx

    Beware: Memecoin risks high

    #blockchain #defi
  agent: twitter_redactor

image_generation_task:
  description: >
    Generate images for the first part of the tweet thread.
    Do not generate graphic content.
    Generate a fictitious image that represents the content of the first part of the tweet thread.
  expected_output: >
    The text generated before with only the image attached at the end
    Using the same structure received
  agent: image_generator
# image_generation_task:
#   description: >
#     Generate images for each part of the tweet thread using Gemini Image Generator.
#     Each image should visually represent the main theme or content of its respective tweet part.
#     The images should maintain consistency in style and theme across the thread.
#   expected_output: >
#     A list of generated images that match each tweet part's content.
#     Each image should be:
#     - Relevant to the tweet part's content
#     - Visually appealing and professional
#     - Consistent with crypto/blockchain theme when applicable
#     - Safe for work and appropriate for social media
#     - Generated in a style that matches the tweet's tone
#   agent: image_generator
